baseurl         = "http://carlosleon.info/"
title           = "Carlos Le√≥n"
theme           = "herring-cove"
googleanalytics = "UA-77086456-2"
disqusshortname = "mongrelion"

# Server-side syntax highlighting config
pygmentscodefences = true
pygmentsstyle      = "autumn"

[params]
  profilepicture = "/img/profile.jpg"
  description    = "Cloud Expert"
  twitter        = "https://twitter.com/mongrelion"
  github         = "https://github.com/mongrelion"
  linkedin       = "https://linkedin.com/in/mongrelion"

[params.links]
  about    = "about/"
  blog     = "articles/"
  readings = "readings/"

[taxonomies]
article = "articles"
reading = "readings"
tag     = "tags"
